### ISSUE TITLE
关系标注任务中，由于关系标签太多，选择关系标签时显示不全

### ISSUE THREAD

**Issue by Zen012479** [cuiwang/MarkStudio#2]

**Comment by cuiwang** [comment]
@hy-god V2.5.2版本中已解决。

**Comment by Zen012479** [comment]
![图片](https://user-images.githubusercontent.com/34857553/160557036-73b16ca2-cf70-4b85-9a0f-4c4ca5038813.png)
大佬，还是有问题的

**Comment by cuiwang** [comment]
好滴，等下将过长的标签做成滑动的。

**Comment by cuiwang** [comment]
2.5.3 已修复。

**Comment by Zen012479** [comment]
谢谢啦
