### ISSUE TITLE
2.5.3版本更新后 序列标注任务出现问题

### ISSUE THREAD

**Issue by Rickey-CS** [cuiwang/MarkStudio#3]
问题：老版本会被强制更新, 不更新的话就是做一个退一次; 更新之后, 标签条没办法拉, 标签不能全部显示；
建议：
1. 建议做成版本列表，以前的稳定版本不要强制更新；
2. 序列标注新产生的问题在前一个版本不存在问题，更新后，标签不能全部显示

**Comment by cuiwang** [comment]
感谢提醒，已经去掉了更新，现在安装旧版本不会提示升级了。此外，新问题中提到的标签条是指哪个地方？
