### ISSUE TITLE
npm run dev 之后报这个错误。无法进入dev模式。

### ISSUE THREAD

**Issue by chriswenwu** [cuiwang/MarkStudio#4]
/www/wwwroot/MarkStudio/node_modules/electron/dist/electron: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory

**Comment by cuiwang** [comment]
完全删除./node_modules文件夹后，重新 `npm install `试试。

**Comment by chriswenwu** [comment]
试过。 还是没用。   node v16.14.0版本  系统是linux环境下

**Comment by cuiwang** [comment]
看日志，好像是缺少动态链接库 libXcomposite.so，看下这个链接：https://www.masmasit.com/2021/08/how-to-install-package-libxcompositeso1.html

**Comment by chriswenwu** [comment]
libXcomposite.i686                                                0.4.4-14.el8                                               appstream    
libXcomposite.x86_64                                              0.4.4-14.el8                                               appstream    
libXcomposite-devel.i686                                          0.4.4-14.el8                                               appstream    
libXcomposite-devel.x86_64                                        0.4.4-14.el8                                               appstream    
下载了还是没用
